wip: homepage
PreMiD/Website pull request #1083
Opened 2024-01-01 06:48 UTC by veryCrunchy

Images are somehow get corrupted on commit✨

2024-01-07 23:23 UTC, veryCrunchy commented
@Bas950 Ready for merge
<details><summary>Preview</summary>
<p>

![image](https://github.com/PreMiD/Website/assets/73395916/769f49c6-0a0f-4d47-8799-e203c18ef8ba)


</p>
</details>

2024-01-08 07:40 UTC, Bas950 requested changes

2024-01-08 07:40 UTC, Bas950 commented on .eslintrc.cjs
> +    "plugin:prettier/recommended",
prettier recommended shouldn't be needed I think

2024-01-08 07:40 UTC, Bas950 commented on .prettierrc
> +}
Maybe use the one from @recodive/configs

2024-01-08 07:40 UTC, Bas950 commented on layouts/default.vue
> +  <div class="font-inter">
Rip nunito?

2024-01-08 07:40 UTC, Bas950 commented on pages/index.vue
> +                        </h1>
Make this text an input in the presenceData thing too (future proofing)

2024-01-08 12:28 UTC, veryCrunchy commented on layouts/default.vue
> +  <div class="font-inter">
Can be changed back if needed. Looks horrible on the homepage tho

2024-01-08 16:27 UTC, veryCrunchy commented on .eslintrc.cjs
> +    "plugin:prettier/recommended",
Added it because it was needed.
Else prettier doesn't work on .vue files.

2024-01-08 16:30 UTC, veryCrunchy commented on .prettierrc
> +}
Will do.
Added because I saw tim use 4 tabwidth.
And default is 2, so it was constantly shifting.

2024-01-08 18:39 UTC, veryCrunchy commented on pages/index.vue
> +                        </h1>
![image](https://github.com/PreMiD/Website/assets/73395916/1be5ddf5-12e4-48f7-9b2a-304f1a68b77b)
Future proofed!!

2024-01-08 18:54 UTC, Bas950 approved these changes

2024-01-08 20:54 UTC, Timeraa requested changes

2024-01-08 20:54 UTC, Timeraa commented on .vscode/settings.json
Why?

2024-01-08 20:59 UTC, veryCrunchy commented on .vscode/settings.json
No one using Spell Checker here? 😭

2024-01-08 23:58 UTC, merged